# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            TechTechTech!
tagline:          'Tech blog'
description:      '기술 블로그입니당.'
url:              https://aksen1312.github.io
baseurl:          /

author:
  name:           'aksen1312'
  url:            https://aksen1312.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://aksen1312.github.io
