# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Tech!
tagline:          'Tech blog'
description:      '기술 블로그입니당.'
url:              https://aksen1312.github.io
baseurl:          /

author:
  name:           'aksen1312'
  url:            https://aksen1312.github.io

paginate:         5

google_analytics: UA-75134277-1

# Custom vars
version:          2.1.0

github:
  repo:           https://aksen1312.github.io
